typography_spectrum: 0.48453128058463335
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.1403813457582146
  lightness: 0.20020364318042994
  saturation: 0.5601134295575321
  rhythmicContrast: 0.7368701708037406
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.21983188926242292
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/558ae98a-6b44-4925-baea-4d1905020a04.jpg
name: Healthy Growth
navigation:
  - name: Shop Now
    url: 'http://www.amway.ca/twintowermotivation'
    type: external
  - name: 'My Credo '
    id: cfc0e53a-ecbb-4e93-b891-324b49ea292a
    type: content
title: Healthy Growth
description: Health - Inside and out
