name: Healthy Growth
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/784b471b-ae80-4137-8121-2a69f49bbc54.png
layout_spectrum: 0.1272854027338326
typography_spectrum: 0.9928274848498404
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.4553982203360647
  lightness: 0.8340550924185663
  saturation: 0.9640310732647777
  rhythmicContrast: 0.5060097011737525
title: Healthy Growth
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: About Us
    url: 'http://healthygrowth.ca/about-us'
    type: external
