typography_spectrum: 0.249886738602072
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5588485351763666
  lightness: 0.9159232908859849
  saturation: 0.9896433504763991
  rhythmicContrast: 0.4482283398974687
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.6626598036382347
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/558ae98a-6b44-4925-baea-4d1905020a04.jpg
name: Healthy Growth
navigation:
  - name: About Us
    url: 'http://healthygrowth.ca/about-us'
    type: external
title: Healthy Growth
description: Growth from the inside out
