layout_spectrum: 0.39274521288461983
typography_spectrum: 0.00883542699739337
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.4001992514822632
  lightness: 0.4688902203924954
  saturation: 0.14864012482576072
  rhythmicContrast: 0.03363971784710884
name: Healthy Growth
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/784b471b-ae80-4137-8121-2a69f49bbc54.png
opengraph:
  type: ''
  appId: ''
title: Healthy Growth
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: About Us
    url: 'http://healthygrowth.ca/about-us'
    type: external
